### ISSUE TITLE
include related fields in response other than custom FETCH

### ISSUE THREAD

**Issue by maikotz** [cs91chris/flask_autocrud#2]
Hi, 

first of all, thanks for the project!
Is it possible to include related fields in GET requests as well?

I want to use Apollo GraphQL on top but can't implement your custom FETCH method there. 

My model is a company that has multiple arrays of id's (users, addresses, invoices, etc). These id's are on other microservices. With FETCH I can easily query them as related ressources.

Or am I missing another way here?

Best regards

models.py
```
class Company(BaseModel):
    __tablename__ = 'company'
    id = Column(Integer, primary_key=True)
    name = Column(String(150), nullable=False, unique=True)
    addresses = relationship("Address", foreign_keys="Address.company_id", back_populates='company')

class Address(BaseModel):
    __tablename__ = 'addresses'
    id = Column(Integer, primary_key=True)
    address_id = Column(Integer)
    company_id = Column(Integer, ForeignKey('company.id'))
    company = relationship("Company", foreign_keys=company_id)
```

curl --request FETCH call
`
{
    "fields": [
        "name"
    ],
    "related": {
        "addresses": [
            "address_id"
        ]
    }
}
`

**Comment by cs91chris** [comment]
Hi,
I do not well understand what output you expect.
The models have to extend the Model class of flask_autocrud (I don't know what your BaseModel is). Your models should look like this (I have not tested):

```
from flask_autocrud import Model

db = SQLAlchemy()


class Company(db.Model, Model):
    __tablename__ = 'company'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False, unique=True)


class Address(db.Model, Model):
    __tablename__ = 'addresses'
    id = db.Column(db.Integer, primary_key=True)
    address_id = db.Column(db.Integer)
    company_id = db.Column(db.Integer, ForeignKey('company.id'))
    company = relationship(Company, backref="addresses")
```

You can see an example, where entities are artists and albums, here https://github.com/cs91chris/flask_autocrud/blob/2f53dc100278ed5318c0db549518806dccd931a8/tests/test_custom.py#L168 

Actually is not possible, with GET method, to fetch multiple related resources and applying filters on it.

Let me know

**Comment by cs91chris** [comment]
Hi @maikotz there is new release available. Now even multiple related resource are retrived with GET.
The following is an example that should fit your need:

``` shell
curl -XGET 'http://127.0.0.1:5000/artist?_related=Album&_fields=Name&_no_links='

{
    "ArtistList": [
        {
            "AlbumList": [
                {
                    "AlbumId": 4
                },
                {
                    "AlbumId": 348
                },
                {
                    "AlbumId": 349
                }
            ],
            "ArtistId": 1,
            "Name": "AC/DC"
        },
        {
            "AlbumList": [
                {
                    "AlbumId": 3
                }
            ],
            "ArtistId": 2,
            "Name": "Accept"
        }
    ]
}
```
